name: Publish to PyPI

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish from'
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          # This ref would be empty (default behaviour) during a workflow_call
          ref: ${{ github.event.inputs.tag }}

      - name: Setup the Python Environment
        uses: Qwerty-133/python-setup@v1
        with:
          python-version: '3.11'
          skip-pre-commit: true

      - name: Publish to PyPI
        run: >
          poetry publish
            --build
            --no-interaction
            --username __token__
            --password '${{ secrets.PYPI_TOKEN }}'
